//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trans2Quik.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trans2Quik.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already connected to Quik..
        /// </summary>
        internal static string AlreadyConnectedToQuik {
            get {
                return ResourceManager.GetString("AlreadyConnectedToQuik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dll connected..
        /// </summary>
        internal static string DllConnected {
            get {
                return ResourceManager.GetString("DllConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dll disconnected..
        /// </summary>
        internal static string DllDisconnected {
            get {
                return ResourceManager.GetString("DllDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dll not connected..
        /// </summary>
        internal static string DllNotConnected {
            get {
                return ResourceManager.GetString("DllNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLL version not supported..
        /// </summary>
        internal static string DllVersionNotSupported {
            get {
                return ResourceManager.GetString("DllVersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed..
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory allocation error..
        /// </summary>
        internal static string MemoryAllocationError {
            get {
                return ResourceManager.GetString("MemoryAllocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quik connected..
        /// </summary>
        internal static string QuikConnected {
            get {
                return ResourceManager.GetString("QuikConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quik disconnected..
        /// </summary>
        internal static string QuikDisconnected {
            get {
                return ResourceManager.GetString("QuikDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quik not connected..
        /// </summary>
        internal static string QuikNotConnected {
            get {
                return ResourceManager.GetString("QuikNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quik terminal not found..
        /// </summary>
        internal static string QuikTerminalNotFound {
            get {
                return ResourceManager.GetString("QuikTerminalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown value..
        /// </summary>
        internal static string UnknownValue {
            get {
                return ResourceManager.GetString("UnknownValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong connection handle..
        /// </summary>
        internal static string WrongConnectionHandle {
            get {
                return ResourceManager.GetString("WrongConnectionHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong input params..
        /// </summary>
        internal static string WrongInputParams {
            get {
                return ResourceManager.GetString("WrongInputParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong syntax..
        /// </summary>
        internal static string WrongSyntax {
            get {
                return ResourceManager.GetString("WrongSyntax", resourceCulture);
            }
        }
    }
}
